#include<iostream>
using namespace std;
main()
{
system("color 01");
cout<<"            %%%%        %%%%    ##### #  #              "<<endl;
cout<<"          %%    %%    %%    %%    #   ####              "<<endl;
cout<<"              %%     %%      %%   #   #  #              "<<endl;
cout<<"            %%      %          %                        "<<endl;
cout<<"         %%%         %%      %%                         "<<endl;
cout<<"         %%%%%%%%%     %%%%%%                           "<<endl;
cout<<"    ------------------------------------------          "<<endl;
cout<<"              C.E.N.T.U.R.Y                             "<<endl;
cout<<"    ------------------------------------------          "<<endl;
cout<<"                                                        "<<endl;
cout<<"          ######### ###### #   # #########              "<<endl;
cout<<"              #     #       # #      #                  "<<endl;
cout<<"              #     ######   #       #                  "<<endl;
cout<<"              #     #       #  #     #                  "<<endl;
cout<<"              #     ###### #    #    #                  "<<endl;
}